# Auto-generated by release-cli.yml — do not edit manually
class KeystoneDiagrams < Formula
  desc "Keystone CLI — diagram and scan your Terraform infrastructure"
  homepage "https://keystone.page"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://keystone-cli-releases.s3.ap-southeast-2.amazonaws.com/cli/v0.1.0/keystone-darwin-arm64"
      sha256 "905bd0f47936faad8b061a12e99de1d197657adbd97135f065fc6d0b3b366ee1"
    end
    on_intel do
      url "https://keystone-cli-releases.s3.ap-southeast-2.amazonaws.com/cli/v0.1.0/keystone-darwin-x64"
      sha256 "811e6a8727f5bc837bf4ad0d48d7e0828c8b2bbfc0cef4fe3d4a82fc32a20500"
    end
  end

  on_linux do
    on_arm do
      url "https://keystone-cli-releases.s3.ap-southeast-2.amazonaws.com/cli/v0.1.0/keystone-linux-arm64"
      sha256 "1848fe05b59f3a43df7d72915e60adc44974a5d491e0b714d5e013aedeafc1ee"
    end
    on_intel do
      url "https://keystone-cli-releases.s3.ap-southeast-2.amazonaws.com/cli/v0.1.0/keystone-linux-x64"
      sha256 "97d0ca40dfc8dc4cc760e87f33c86febcc290279e8ffb52c620f6012efb8a37d"
    end
  end

  def install
    bin.install Dir["keystone-*"].first => "keystone"
  end

  test do
    system "#{bin}/keystone", "--help"
  end
end