# Auto-generated by release-cli.yml — do not edit manually
class Keystone < Formula
  desc "Keystone CLI — diagram and scan your Terraform infrastructure"
  homepage "https://keystone.page"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://keystone-cli-releases.s3.ap-southeast-2.amazonaws.com/cli/v0.2.0/keystone-darwin-arm64"
      sha256 "c62591b34f16d8329cc3eef99700b3c18909a94ced19c4595928c40ca382a207"
    end
    on_intel do
      url "https://keystone-cli-releases.s3.ap-southeast-2.amazonaws.com/cli/v0.2.0/keystone-darwin-x64"
      sha256 "bff7497a9ad6f28a1ad917e24017fda6993964d32be6363d1bbf824066903e2a"
    end
  end

  on_linux do
    on_arm do
      url "https://keystone-cli-releases.s3.ap-southeast-2.amazonaws.com/cli/v0.2.0/keystone-linux-arm64"
      sha256 "a5f408ada600a1e380010a8614af9f34077ec863744522c5722be7680cc3d1f0"
    end
    on_intel do
      url "https://keystone-cli-releases.s3.ap-southeast-2.amazonaws.com/cli/v0.2.0/keystone-linux-x64"
      sha256 "c3ffd4501af51a6aa2b0f100f32d15ed1722a8138659ca346e028d3741884ecd"
    end
  end

  def install
    bin.install Dir["keystone-*"].first => "keystone"
  end

  test do
    system "#{bin}/keystone", "--help"
  end
end